// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ApiKey is the golang structure of table api_key for DAO operations like Where/Data.
type ApiKey struct {
	g.Meta   `orm:"table:api_key, do:true"`
	Id       interface{} //
	Key      interface{} //
	Value    interface{} //
	CreateAt *gtime.Time //
}
