// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Banalyze is the golang structure of table banalyze for DAO operations like Where/Data.
type Banalyze struct {
	g.Meta      `orm:"table:banalyze, do:true"`
	Id          interface{} //
	Key         interface{} //
	Description interface{} //
	Value       interface{} //
	CreateAt    *gtime.Time //
}
