// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanWeb is the golang structure of table scan_web for DAO operations like Where/Data.
type ScanWeb struct {
	g.Meta         `orm:"table:scan_web, do:true"`
	Id             interface{} //
	CusName        interface{} //
	Url            interface{} //
	Code           interface{} //
	Title          interface{} //
	ContentLength  interface{} //
	Fingerprint    interface{} //
	Image          interface{} //
	ScreenshotFlag interface{} //
	Js             interface{} //
	Urls           interface{} //
	Forms          interface{} //
	Secret         interface{} //
	Flag           interface{} //
	NsqFlag        interface{} //
	ScanFlag       interface{} //
	ScanNsqFlag    interface{} //
	CreateAt       *gtime.Time //
}
