// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanPort is the golang structure of table scan_port for DAO operations like Where/Data.
type ScanPort struct {
	g.Meta        `orm:"table:scan_port, do:true"`
	Id            interface{} //
	CusName       interface{} //
	Host          interface{} //
	Port          interface{} //
	ServiceName   interface{} //
	VendorProduct interface{} //
	Version       interface{} //
	Flag          interface{} //
	NsqFlag       interface{} //
	HttpFlag      interface{} //
	Url           interface{} //
	Code          interface{} //
	Title         interface{} //
	CrackFlag     interface{} //
	CrackNsqFlag  interface{} //
	ScanFlag      interface{} //
	ScanNsqFlag   interface{} //
	CreateAt      *gtime.Time //
}
