// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanSubdomain is the golang structure of table scan_subdomain for DAO operations like Where/Data.
type ScanSubdomain struct {
	g.Meta    `orm:"table:scan_subdomain, do:true"`
	Id        interface{} //
	CusName   interface{} //
	Domain    interface{} //
	Subdomain interface{} //
	Ip        interface{} //
	Cname     interface{} //
	Cdn       interface{} //
	Location  interface{} //
	Flag      interface{} //
	NsqFlag   interface{} //
	CreateAt  *gtime.Time //
}
