// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanHome is the golang structure of table scan_home for DAO operations like Where/Data.
type ScanHome struct {
	g.Meta    `orm:"table:scan_home, do:true"`
	Id        interface{} //
	CusName   interface{} //
	CusRemark interface{} //
	CreateAt  *gtime.Time //
}
