// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanDomain is the golang structure of table scan_domain for DAO operations like Where/Data.
type ScanDomain struct {
	g.Meta   `orm:"table:scan_domain, do:true"`
	Id       interface{} //
	CusName  interface{} //
	Domain   interface{} //
	Flag     interface{} //
	NsqFlag  interface{} //
	CreateAt *gtime.Time //
}
