// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOperation is the golang structure of table user_operation for DAO operations like Where/Data.
type UserOperation struct {
	g.Meta   `orm:"table:user_operation, do:true"`
	Id       interface{} //
	Username interface{} //
	Ip       interface{} //
	Theme    interface{} //
	Content  interface{} //
	CreateAt *gtime.Time //
}
