// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserIp is the golang structure of table user_ip for DAO operations like Where/Data.
type UserIp struct {
	g.Meta   `orm:"table:user_ip, do:true"`
	Id       interface{} //
	Ip       interface{} //
	Lock     interface{} //
	CreateAt *gtime.Time //
}
