// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserLog is the golang structure of table user_log for DAO operations like Where/Data.
type UserLog struct {
	g.Meta    `orm:"table:user_log, do:true"`
	Id        interface{} //
	Username  interface{} //
	Ip        interface{} //
	UserAgent interface{} //
	CreateAt  *gtime.Time //
}
