// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UtilPortscanTask is the golang structure of table util_portscan_task for DAO operations like Where/Data.
type UtilPortscanTask struct {
	g.Meta   `orm:"table:util_portscan_task, do:true"`
	Id       interface{} //
	CusName  interface{} //
	HostNum  interface{} //
	ScanNum  interface{} //
	CreateAt *gtime.Time //
}
