// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UtilSubdomainTask is the golang structure of table util_subdomain_task for DAO operations like Where/Data.
type UtilSubdomainTask struct {
	g.Meta    `orm:"table:util_subdomain_task, do:true"`
	Id        interface{} //
	CusName   interface{} //
	DomainNum interface{} //
	ScanNum   interface{} //
	CreateAt  *gtime.Time //
}
