// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalBanalyzeDao is do type for wrapping do DAO implements.
type internalBanalyzeDao = *internal.BanalyzeDao

// banalyzeDao is the data access object for table banalyze.
// You can define custom methods on it to extend its functionality as you wish.
type banalyzeDao struct {
	internalBanalyzeDao
}

var (
	// Banalyze is globally public accessible object for table banalyze operations.
	Banalyze = banalyzeDao{
		internal.NewBanalyzeDao(),
	}
)

// Fill with you ideas below.
