// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalScanWebDao is internal type for wrapping internal DAO implements.
type internalScanWebDao = *internal.ScanWebDao

// scanWebDao is the data access object for table scan_web.
// You can define custom methods on it to extend its functionality as you wish.
type scanWebDao struct {
	internalScanWebDao
}

var (
	// ScanWeb is globally public accessible object for table scan_web operations.
	ScanWeb = scanWebDao{
		internal.NewScanWebDao(),
	}
)

// Fill with you ideas below.
