// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalScanDomainDao is do type for wrapping do DAO implements.
type internalScanDomainDao = *internal.ScanDomainDao

// scanDomainDao is the data access object for table scan_domain.
// You can define custom methods on it to extend its functionality as you wish.
type scanDomainDao struct {
	internalScanDomainDao
}

var (
	// ScanDomain is globally public accessible object for table scan_domain operations.
	ScanDomain = scanDomainDao{
		internal.NewScanDomainDao(),
	}
)

// Fill with you ideas below.
