// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalScanSubdomainDao is internal type for wrapping internal DAO implements.
type internalScanSubdomainDao = *internal.ScanSubdomainDao

// scanSubdomainDao is the data access object for table scan_subdomain.
// You can define custom methods on it to extend its functionality as you wish.
type scanSubdomainDao struct {
	internalScanSubdomainDao
}

var (
	// ScanSubdomain is globally public accessible object for table scan_subdomain operations.
	ScanSubdomain = scanSubdomainDao{
		internal.NewScanSubdomainDao(),
	}
)

// Fill with you ideas below.
