// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalUserIpDao is internal type for wrapping internal DAO implements.
type internalUserIpDao = *internal.UserIpDao

// userIpDao is the data access object for table user_ip.
// You can define custom methods on it to extend its functionality as you wish.
type userIpDao struct {
	internalUserIpDao
}

var (
	// UserIp is globally public accessible object for table user_ip operations.
	UserIp = userIpDao{
		internal.NewUserIpDao(),
	}
)

// Fill with you ideas below.
