// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalUserLogDao is internal type for wrapping internal DAO implements.
type internalUserLogDao = *internal.UserLogDao

// userLogDao is the data access object for table user_log.
// You can define custom methods on it to extend its functionality as you wish.
type userLogDao struct {
	internalUserLogDao
}

var (
	// UserLog is globally public accessible object for table user_log operations.
	UserLog = userLogDao{
		internal.NewUserLogDao(),
	}
)

// Fill with you ideas below.
