// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather/internal/dao/internal"
)

// internalUtilSubdomainTaskDao is internal type for wrapping internal DAO implements.
type internalUtilSubdomainTaskDao = *internal.UtilSubdomainTaskDao

// utilSubdomainTaskDao is the data access object for table util_subdomain_task.
// You can define custom methods on it to extend its functionality as you wish.
type utilSubdomainTaskDao struct {
	internalUtilSubdomainTaskDao
}

var (
	// UtilSubdomainTask is globally public accessible object for table util_subdomain_task operations.
	UtilSubdomainTask = utilSubdomainTaskDao{
		internal.NewUtilSubdomainTaskDao(),
	}
)

// Fill with you ideas below.
