// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UtilPortscanTaskDao is the data access object for table util_portscan_task.
type UtilPortscanTaskDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns UtilPortscanTaskColumns // columns contains all the column names of Table for convenient usage.
}

// UtilPortscanTaskColumns defines and stores column names for table util_portscan_task.
type UtilPortscanTaskColumns struct {
	Id       string //
	CusName  string //
	HostNum  string //
	ScanNum  string //
	CreateAt string //
}

// utilPortscanTaskColumns holds the columns for table util_portscan_task.
var utilPortscanTaskColumns = UtilPortscanTaskColumns{
	Id:       "id",
	CusName:  "cus_name",
	HostNum:  "host_num",
	ScanNum:  "scan_num",
	CreateAt: "create_at",
}

// NewUtilPortscanTaskDao creates and returns a new DAO object for table data access.
func NewUtilPortscanTaskDao() *UtilPortscanTaskDao {
	return &UtilPortscanTaskDao{
		group:   "default",
		table:   "util_portscan_task",
		columns: utilPortscanTaskColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UtilPortscanTaskDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UtilPortscanTaskDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UtilPortscanTaskDao) Columns() UtilPortscanTaskColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UtilPortscanTaskDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UtilPortscanTaskDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UtilPortscanTaskDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
