// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Rewriterl/ifgather-server/internal/dao/internal"
)

// internalScanHomeDao is do type for wrapping do DAO implements.
type internalScanHomeDao = *internal.ScanHomeDao

// scanHomeDao is the data access object for table scan_home.
// You can define custom methods on it to extend its functionality as you wish.
type scanHomeDao struct {
	internalScanHomeDao
}

var (
	// ScanHome is globally public accessible object for table scan_home operations.
	ScanHome = scanHomeDao{
		internal.NewScanHomeDao(),
	}
)

// Fill with you ideas below.
