// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ApiKey is the golang structure for table api_key.
type ApiKey struct {
	Id       int         `json:"id"       ` //
	Key      string      `json:"key"      ` //
	Value    string      `json:"value"    ` //
	CreateAt *gtime.Time `json:"createAt" ` //
}
