// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Banalyze is the golang structure for table banalyze.
type Banalyze struct {
	Id          int         `json:"id"          ` //
	Key         string      `json:"key"         ` //
	Description string      `json:"description" ` //
	Value       string      `json:"value"       ` //
	CreateAt    *gtime.Time `json:"createAt"    ` //
}
