// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanPort is the golang structure for table scan_port.
type ScanPort struct {
	Id            int         `json:"id"            ` //
	CusName       string      `json:"cusName"       ` //
	Host          string      `json:"host"          ` //
	Port          int         `json:"port"          ` //
	ServiceName   string      `json:"serviceName"   ` //
	VendorProduct string      `json:"vendorProduct" ` //
	Version       string      `json:"version"       ` //
	Flag          bool        `json:"flag"          ` //
	NsqFlag       bool        `json:"nsqFlag"       ` //
	HttpFlag      bool        `json:"httpFlag"      ` //
	Url           string      `json:"url"           ` //
	Code          int         `json:"code"          ` //
	Title         string      `json:"title"         ` //
	CrackFlag     bool        `json:"crackFlag"     ` //
	CrackNsqFlag  bool        `json:"crackNsqFlag"  ` //
	ScanFlag      bool        `json:"scanFlag"      ` //
	ScanNsqFlag   bool        `json:"scanNsqFlag"   ` //
	CreateAt      *gtime.Time `json:"createAt"      ` //
}
