// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanDomain is the golang structure for table scan_domain.
type ScanDomain struct {
	Id       int         `json:"id"       ` //
	CusName  string      `json:"cusName"  ` //
	Domain   string      `json:"domain"   ` //
	Flag     bool        `json:"flag"     ` //
	NsqFlag  bool        `json:"nsqFlag"  ` //
	CreateAt *gtime.Time `json:"createAt" ` //
}
