// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanHome is the golang structure for table scan_home.
type ScanHome struct {
	Id        int         `json:"id"        ` //
	CusName   string      `json:"cusName"   ` //
	CusRemark string      `json:"cusRemark" ` //
	CreateAt  *gtime.Time `json:"createAt"  ` //
}
