// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ScanSubdomain is the golang structure for table scan_subdomain.
type ScanSubdomain struct {
	Id        int         `json:"id"        ` //
	CusName   string      `json:"cusName"   ` //
	Domain    string      `json:"domain"    ` //
	Subdomain string      `json:"subdomain" ` //
	Ip        string      `json:"ip"        ` //
	Cname     string      `json:"cname"     ` //
	Cdn       bool        `json:"cdn"       ` //
	Location  string      `json:"location"  ` //
	Flag      bool        `json:"flag"      ` //
	NsqFlag   bool        `json:"nsqFlag"   ` //
	CreateAt  *gtime.Time `json:"createAt"  ` //
}
