// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id       int         `json:"id"       ` //
	Username string      `json:"username" ` //
	Password string      `json:"password" ` //
	NickName string      `json:"nickName" ` //
	Phone    string      `json:"phone"    ` //
	Email    string      `json:"email"    ` //
	Remark   string      `json:"remark"   ` //
	CreateAt *gtime.Time `json:"createAt" ` //
}
