// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserLog is the golang structure for table user_log.
type UserLog struct {
	Id        int         `json:"id"        ` //
	Username  string      `json:"username"  ` //
	Ip        string      `json:"ip"        ` //
	UserAgent string      `json:"userAgent" ` //
	CreateAt  *gtime.Time `json:"createAt"  ` //
}
