// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOperation is the golang structure for table user_operation.
type UserOperation struct {
	Id       int         `json:"id"       ` //
	Username string      `json:"username" ` //
	Ip       string      `json:"ip"       ` //
	Theme    string      `json:"theme"    ` //
	Content  string      `json:"content"  ` //
	CreateAt *gtime.Time `json:"createAt" ` //
}
