// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserIp is the golang structure for table user_ip.
type UserIp struct {
	Id       int         `json:"id"       ` //
	Ip       string      `json:"ip"       ` //
	Lock     int         `json:"lock"     ` //
	CreateAt *gtime.Time `json:"createAt" ` //
}
