// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UtilSubdomainTask is the golang structure for table util_subdomain_task.
type UtilSubdomainTask struct {
	Id        int         `json:"id"        ` //
	CusName   string      `json:"cusName"   ` //
	DomainNum int         `json:"domainNum" ` //
	ScanNum   int         `json:"scanNum"   ` //
	CreateAt  *gtime.Time `json:"createAt"  ` //
}
