// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UtilPortscanTask is the golang structure for table util_portscan_task.
type UtilPortscanTask struct {
	Id       int         `json:"id"       ` //
	CusName  string      `json:"cusName"  ` //
	HostNum  int         `json:"hostNum"  ` //
	ScanNum  int         `json:"scanNum"  ` //
	CreateAt *gtime.Time `json:"createAt" ` //
}
